<template>
  <form @submit.prevent="submitForm" class="space-y-4">

    <div class="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mt-4" role="alert">
      <p class="font-bold">⚠️ Disclaimer</p>
      <p>This application was created by someone without a medical background. The analysis results are generated by AI and are for informational purposes only. It is strongly recommended to consult with a qualified medical professional for any health-related actions or decisions.</p>
      <p>Aplikasi ini dibuat oleh seseorang tanpa latar belakang medis. Hasil analisis dihasilkan oleh AI dan hanya untuk tujuan informasi. Sangat disarankan untuk berkonsultasi dengan tenaga medis profesional yang berkualifikasi sebelum melakukan tindakan atau keputusan terkait kesehatan apa pun.</p>
    </div>

    <div>
      <label class="block text-sm font-medium mb-1">Model AI</label>
      <select v-model="form.llm" class="w-full border rounded-md p-2">
        <option disabled value="">-- Pilih AI --</option>
        <option value="gemini">Gemini</option>
        <option value="groq">Groq</option>
        <option value="openai">OpenAi</option>
      </select>
    </div>

    <div>
      <label class="block text-sm font-medium mb-1">Jenis Kelamin (Gender)</label>
      <select v-model="form.gender" class="w-full border rounded-md p-2">
        <option disabled value="">-- Pilih Gender --</option>
        <option value="male">Laki-laki</option>
        <option value="female">Perempuan</option>
      </select>
    </div>

    <div>
      <label class="block text-sm font-medium mb-1">Umur (Age)</label>
      <input
        v-model="form.age"
        type="number"
        min="0"
        class="w-full border rounded-md p-2"
        placeholder="Enter patient age"
      />
    </div>

    <div>
      <label class="block text-sm font-medium mb-1">Gejala (Symptoms)</label>
      <div class="flex gap-2">
        <input
          v-model="symptomInput"
          @keyup.enter="addSymptom"
          type="text"
          class="flex-1 border rounded-md p-2"
          placeholder="Enter symptom and press Enter or click Add"
        />
        <button
          type="button"
          @click="addSymptom"
          :disabled="!symptomInput.trim()"
          class="bg-green-500 hover:bg-green-600 disabled:bg-gray-300 text-white px-4 py-2 rounded-md"
        >
          Masukan Gejala
        </button>
      </div>
      <div class="flex flex-wrap gap-2 mt-2">
        <span
          v-for="(symptom, index) in form.symptoms"
          :key="index"
          class="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm flex items-center"
        >
          {{ symptom }}
          <button
            type="button"
            @click="removeSymptom(index)"
            class="ml-2 text-red-500 hover:text-red-700"
          >
            ✕
          </button>
        </span>
      </div>
    </div>

    <button
      type="submit"
      :disabled="loading"
      class="bg-blue-600 hover:bg-blue-700 text-white font-semibold w-full py-2 rounded-md transition"
    >
      {{ loading ? 'Analyzing...' : 'Get Recommendation' }}
    </button>

    <div v-if="error" class="text-red-500 mt-3 text-center">
      ⚠️ {{ error }}
    </div>

    <div v-if="result.recommended_department" class="mt-4">
      <h2 class="text-lg font-medium text-gray-700 mb-2">Departemen yg berhubungan (Recommended Department):</h2>
      <ul class="list-disc list-inside text-blue-600">
        <li v-for="dept in result.recommended_department" :key="dept">{{ dept }}</li>
      </ul>
    </div>

    <div v-if="result.possibility_of_illness" class="mt-4">
      <h2 class="text-lg font-medium text-gray-700 mb-2">Kemungkinan Penyakit (Possibility of Illness):</h2>
      <ul class="list-disc list-inside text-red-600">
        <li v-for="illness in result.possibility_of_illness" :key="illness">{{ illness }}</li>
      </ul>
    </div>

    <div v-if="result.initial_handling" class="mt-4">
      <h2 class="text-lg font-medium text-gray-700 mb-2">Rekomendasi Penanganan Awal (Initial Handling):</h2>
      <ul class="list-disc list-inside text-green-600">
        <li v-for="handling in result.initial_handling" :key="handling">{{ handling }}</li>
      </ul>
    </div>
  </form>
</template>

<script setup>
import axios from 'axios'
import { ref } from 'vue'

const form = ref({
  llm: '',
  gender: '',
  age: '',
  symptoms: []
})
const symptomInput = ref('')
const result = ref({})
const loading = ref(false)
const error = ref('')

const addSymptom = () => {
  if (symptomInput.value.trim() && !form.value.symptoms.includes(symptomInput.value)) {
    form.value.symptoms.push(symptomInput.value.trim())
    symptomInput.value = ''
  }
}

const removeSymptom = (index) => {
  form.value.symptoms.splice(index, 1)
}

const submitForm = async () => {
  result.value = {}
  error.value = ''
  loading.value = true

  try {
    const { data } = await axios.post('/api/recommend', form.value, {
      timeout: 10000 // ⏱ frontend timeout juga 10 detik
    })
    result.value = data
  } catch (err) {
    if (err.code === 'ECONNABORTED') {
      error.value = 'Request timed out. Please try again.'
    } else {
      error.value = err.response?.data?.detail || 'Error contacting server.'
    }
  } finally {
    loading.value = false
  }
}
</script>
